### ISSUE TITLE
Boundaries in headers and body are different when setting Content-Type explicitly

### ISSUE THREAD

**Issue by jagaapple** [ishkawa/APIKit#248]
In the case using `multipart/form-data` MIME type and setting Content-Type using `MultipartFormDataBodyParameters.contentType` at `headerFields` , boundaries in the request body are different from header's boundary.

---

```swift
protocol MyRequestType: Request {
  var multipartFormDataBodyParameters: MultipartFormDataBodyParameters? { get }
}

extension MyRequestType {
  var headerFields: [String: String] {
    return [
      "Accept": "application/json",
      "Accept-Encoding": "gzip",
      "Content-Type": self.multipartFormDataBodyParameters?.contentType ?? "application/json",
    ]
  }
  var bodyParameters: BodyParameters? { return self.multipartFormDataBodyParameters }
  var multipartFormDataBodyParameters: MultipartFormDataBodyParameters? { return nil }
}
```

```swift
struct JSONRequest: MyRequestType {
  var method: HTTPMethod { return .post }
  ...
  var bodyParameters: BodyParameters? {
    return JSONBodyParameters(JSONObject: [
      "name": "foo",
    ])
  }
  ...
}

struct MultipartFormDataRequest: MyRequestType {
  var method: HTTPMethod { return .post }
  ...
  var multipartFormDataBodyParameters: MultipartFormDataBodyParameters? {
    return MultipartFormDataBodyParameters(parts: [
      MultipartFormDataBodyParameters.Part(data: "bar".data(using: .utf8)!, name: "name"),
    ])
  }
  ...

  func intercept(urlRequest: URLRequest) throws -> URLRequest {
    urlRequest.allHTTPHeaderFields
    // [0] = (key = "Content-Type", value = "multipart/form-data; boundary=xxxx")
    // ...
   
    String(data: urlRequest.httpBody!, encoding: .utf8)
    // --yyy
    // Content-Disposition: form-data; name="name"
    //
    // bar
    // --yyy--

    // !! Header's boundary is "xxx", but body's boundaries are "yyy" !!

    return urlRequest
  }
}
```

The codes setting at Content-Type explicitly like the above do not work, but removing it works fine.

```swift
extension MyRequestType {
  var headerFields: [String: String] {
    return [
      "Accept": "application/json",
      "Accept-Encoding": "gzip",
      // "Content-Type": self.multipartFormDataBodyParameters?.contentType ?? "application/json",
      // Remove the above code.
      // And be set a parameter automatically by APIKit.
    ]
  }
```

Maybe these behaviors are bugs, I report them ;)

**Comment by ishkawa** [comment]
Hi, @jagaapple. Thank you for reporting issue.

I guess this issue is caused by multiple access to `multipartFormDataBodyParameters`:
- `urlRequest.allHTTPHeaderFields`
- `String(data: urlRequest.httpBody!, encoding: .utf8)`

Your code always creates a new instance of MultipartFormDataBodyParameters when `multipartFormDataBodyParameters` is accessed. So if we get value from `multipartFormDataBodyParameters` multiple times, the values are different from each other.

To prevent this, we have 2 choices:

1. Always return the same value in `multipartFormDataBodyParameters`.
1. Avoid multiple access to `multipartFormDataBodyParameters`.

I think 1 will fit your usage because you need explicit `Content-Type`.

**Comment by jagaapple** [comment]
Hi @ishkawa, thank you for your reply and explanations.
Oh! It is exactly as you say, it creates new instance objects every access, so this is not a bug!

Thank you for reading my poor issue X(
