### ISSUE TITLE
Can't install by copying source files

### ISSUE THREAD

**Issue by sagaraya** [ishkawa/APIKit#40]
To use iOS7, I try to install manualy.

> Copy APIKit/*.swift and Carthage/Checkouts/Result/Result/*.swift to your project.

https://github.com/ishkawa/APIKit#3-copying-source-files

But I can't find `Carthage/Checkouts/Result/Result/*.swift` after `git clone`
```
$ ls Carthage/Checkouts/
Assertions  OHHTTPStubs
```

after `carthage update` 

```
$ ls Carthage/Checkouts/
Assertions Result
```

But still has error on `import Box` in Result.swift
`Swift Compiler Error No such module 'Box'`

So, I added Box.swift, BoxType.swift, MutableBox.swift.
And commented out `import Box`

Then build succeeded.

Please modify document or code to install more easily.

（英語下手くそなので、もしわかりづらかったら日本語で補足します。個人的には[Alamofireみたくgit submoduleでインストール](http://dev.classmethod.jp/references/swift-oss-alamofire-1/)できたらうれしいです。ちょっと試したのですがAPIKit.hが赤いテキストになり、うまくいきませんでした）

**Comment by ishkawa** [comment]
@sagaraya Thank you for reporting! We try to make this issue clear.

@ikesyo I appreciate #41. Unfortunately, we are still unable to install APIKit by copying source files because Result.framework contains `import Box`. It means we have to modify code of Result.framework to support this installation, but this is undesirable for me. In short, we can support installation using dynamic framework only, so I think instructions about copying source files should be removed. 

BTW, as @sagaraya suggested, we should also provide installation using git submodule. I will try to make Xcode project independent of Carthage in a few days.

**Comment by ishkawa** [comment]
@sagaraya We've completed to support embedding Xcode project! Check out https://github.com/ishkawa/APIKit#3-embedding-project to see specific instructions.

**Comment by sagaraya** [comment]
@ishkawa Thank you. I check document and understand APIKit support iOS8 or later.
